In [1]:
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

In [2]:
#load training data
train_input_temp2 = pd.read_csv('EI_training_input.csv',header=None)
#train_output_temp = pd.read_csv('EI_training_output_data.csv',header=None)
train_output_temp2 = pd.read_csv('EI_training_output.csv',header=None)

train_application_temp = pd.read_csv('EI_application_input.csv',header=None)

In [3]:
train_input=np.array(train_input_temp2)
train_application=np.array(train_application_temp)
#train_input

In [4]:
train_output=np.array(train_output_temp2)#
train_output[[1,5],:]

array([[0., 0., 1.],
       [0., 0., 1.]])

In [5]:
model = LinearRegression().fit(train_input,train_output)

In [6]:
r_sq = model.score(train_input,train_output)
r_sq

0.3582154196428378

In [7]:
y_pred = model.predict(train_input)
y_appl = model.predict(train_application)
y_pred

array([[ 0.01704996,  0.83135543,  0.15159461],
       [ 0.19693879,  0.1674611 ,  0.6356001 ],
       [ 0.72486261,  0.46416883, -0.18903144],
       [ 0.19693879,  0.1674611 ,  0.6356001 ],
       [ 0.59104897,  0.14386116,  0.26508986],
       [ 0.04956386,  0.76200686,  0.18842928],
       [-0.1580099 ,  0.44681825,  0.71119166],
       [-0.08123678,  0.68437069,  0.39686609],
       [ 0.36547362,  0.11428352,  0.52024285],
       [ 0.00831764,  0.69777734,  0.29390502],
       [ 0.33295973,  0.18363209,  0.48340818],
       [ 0.14433857,  0.71394833,  0.1417131 ],
       [ 0.46376036,  0.26126826,  0.27497137],
       [ 0.14433857,  0.71394833,  0.1417131 ],
       [ 0.59104897,  0.14386116,  0.26508986],
       [ 0.17685247,  0.64459976,  0.17854777],
       [ 0.01704996,  0.83135543,  0.15159461],
       [ 0.14433857,  0.71394833,  0.1417131 ],
       [ 0.72486261,  0.46416883, -0.18903144],
       [-0.54338776,  0.60399627,  0.93939149],
       [ 0.01704996,  0.83135543,  0.151

In [8]:
result      = y_pred.argmax(axis=1).astype(int)
result_appl = y_appl.argmax(axis=1).astype(int)
result

array([1, 2, 0, 2, 0, 1, 2, 1, 2, 1, 2, 1, 0, 1, 0, 1, 1, 1, 0, 2, 1, 0,
       0, 2, 2, 0, 1, 0, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 1, 1, 0, 1])

In [9]:
result_appl

array([1, 2, 2, 0, 1, 1, 1, 1, 1, 0, 0, 0])

In [10]:
output=train_output.argmax(axis=1).astype(int)

In [11]:
diff=result-output
diff

array([ 0,  0,  0,  0, -1, -1,  0,  0,  2,  0,  0,  0, -1,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, -1,  0,  0,
        0,  1,  1,  0,  0,  0,  0,  0,  0,  0])

In [12]:
print(np.count_nonzero(diff),' over', len(diff),' samples')

9  over 44  samples
