In [1]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import mxnet as mx
from mxnet import nd
from mxnet.gluon import nn
import numpy as np
import sys
import json

/home/chao2/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
data = pd.read_csv('EI_application_input.csv',header=None)
data

0    1    2    3    4    5
0   1.0  1.0  0.0  1.0  1.0  1.0
1   0.0  1.0  0.0  0.0  0.0  0.0
2   0.0  1.0  0.0  0.0  0.0  0.0
3   0.0  1.0  0.0  1.0  0.0  1.0
4   1.0  1.0  0.0  1.0  1.0  1.0
5   0.0  1.0  0.0  1.0  1.0  0.0
6   0.0  1.0  0.0  1.0  0.0  0.0
7   1.0  1.0  1.0  1.0  1.0  1.0
8   1.0  1.0  0.0  1.0  0.0  1.0
9   0.0  0.0  1.0  1.0  1.0  1.0
10  0.0  1.0  0.0  0.0  0.0  1.0
11  0.0  0.0  0.0  0.0  1.0  1.0

In [3]:
print("audit_deltaEI.data") 
p=pd.read_pickle("audit_deltaEI.data")

audit_deltaEI.data


In [4]:
ctx = mx.cpu()
layer = nn.Sequential()
with layer.name_scope():
    layer.add(
        nn.Dense(6, activation="relu"),
        nn.Dropout(0.5),          # dropout to ease the overfitting problem
        nn.Dense(3)
    )
layer.load_parameters('audit_deltaEI.params',ctx)

In [5]:
predict=nd.array(data)
predict


[[1. 1. 0. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1.]
 [0. 1. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1.]]
<NDArray 12x6 @cpu(0)>

In [6]:
result=layer(predict).argmax(axis=1).astype(int)
sys.stdout.write(json.dumps(result.asnumpy().tolist()))

[1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1]

In [7]:
#if dEI_temp > 10.0:
#    result_matrix[nb_etat] = [1,0,0]
#elif dEI_temp < -10.0:
#    result_matrix[nb_etat] = [0,0,1]
#else:
#    result_matrix[nb_etat] = [0,1,0]

In [8]:
if result[0]==0:
    print('The EI is increasing')
elif result[0]==1:
    print('The EI is stable')
else:
    print('The EI is decreasing')


The EI is stable
